# This file configures the analyzer to use the lint rule set from `package:lint`

include: package:lint/strict.yaml # For production apps

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"

# You can customize the lint rules set to your own liking. A list of all rules
# can be found at https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    # Util classes are awesome!
    # avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: true

    prefer_single_quotes: true
