# This file configures the analyzer to use the lint rule set from `package:lint`

include: package:lint/strict.yaml # For production apps

analyzer:
  exclude:
    - "*/firebase_options.dart"
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.config.dart"
    - "*/generated"

# You can customize the lint rules set to your own liking. A list of all rules
# can be found at https://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    sort_pub_dependencies: false
    sort_constructors_first: true
    prefer_single_quotes: true
    depend_on_referenced_packages: false
    directives_ordering: false