name: debt_tracker
description: Debts - Debt Tracker

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: 1.0.5

  flutter:
    sdk: flutter

  # State management
  flutter_bloc: 8.1.3

  # Dependencies injection
  get_it: 7.6.0
  injectable: 2.1.2

  # Navigation
  auto_route: 7.4.0

  # Utils
  rxdart: 0.27.7
  dartx: 1.1.0
  dartz: 0.10.1
  freezed_annotation: 2.2.0

  # Networking
  dio: 5.2.0
  retrofit: 4.0.1
  json_annotation: 4.8.1

  # Localizations
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: 2.4.4
  injectable_generator: 2.1.6
  freezed: 2.3.5
  json_serializable: 6.7.0
  retrofit_generator: 7.0.1
  auto_route_generator: 7.1.1

  # Code rules
  lint: 2.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        

