name: debt_tracker
description: Debts - Debt Tracker

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: 1.0.5

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State management
  flutter_bloc: 8.1.3

  # Dependencies injection
  get_it: 7.6.0
  injectable: 2.1.2

  # UI
  flutter_animate: 4.1.1+1
  extended_sliver: 2.1.3
  sliver_tools: 0.2.10
  flutter_sticky_header: 0.6.5
  font_awesome_flutter: 10.4.0

  # Navigation
  auto_route: 7.4.0

  # Utils
  rxdart: 0.27.7
  dartx: 1.1.0
  dartz: 0.10.1
  logger: 1.4.0
  freezed_annotation: 2.2.0
  auto_mappr_annotation: 1.1.0
  gap: 3.0.0
  flutter_svg: 2.0.7
  flutter_keyboard_visibility: ^5.4.1

  # Networking
  dio: 5.2.1+1
  retrofit: 4.0.1
  json_annotation: 4.8.1

  # Localizations
  intl: 0.18.0

  # Animations
  lottie: 2.4.0

  # Firebase
  firebase_core: 2.14.0
  firebase_crashlytics: 3.3.3
  firebase_auth: 4.6.3
  google_sign_in: 6.1.4

  # Testing
  mockito: 5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: 2.4.5
  injectable_generator: 2.1.6
  freezed: 2.3.5
  json_serializable: 6.7.0
  retrofit_generator: 7.0.1
  auto_route_generator: 7.1.1
  auto_mappr: 1.4.0

  # Code rules
  lint: 2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
  localizely:
    project_id: 021dee1f-058d-466c-8f6a-dbfcc899e785
